[build-system]
requires = [
    "setuptools>=45",
    "wheel",
    "setuptools_scm>=6.2",
]
build-backend = "setuptools.build_meta"

[project]
name = "gtfs-fetcher"
version = "0.1.0"
description = "Download, validate, and manage GTFS transit feeds"
readme = "README.rst"
requires-python = ">=3.10"
license = {file = "LICENSE.txt"}
authors = [
  {email = "nils@gis-ops.com"}
]
maintainers = [
  {name = "Nils Nolde", email = "nils@gis-ops.com"}
]

dependencies = [
"prettytable >= 3.7.0, < 4.0.0",
"requests >= 2.22.0, < 3.0.0",
"typer[all] >= 0.9.0, < 1.0.0",
"chalky >= 1.0.0, < 2.0.0",
"halo >= 0.0.29, < 0.1.0"
]

[project.optional-dependencies]
socks = [ 'PySocks >= 1.5.6, != 1.5.7, < 2' ]
tests = [
  'ddt >= 1.2.2, < 2',
  'pytest < 6',
  'mock >= 1.0.1, < 4; python_version < "3.4"',
]
lint = [
  "pre-commit >= 2.20.0" 
]
